version: '3.0'

services:
  web:
    container_name: flask_app
    build:
      context: ./app
    networks:
      custom_net:
        ipv4_address: 192.168.1.10
    ports:
      - “5000:5000”

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      custom_net:
        ipv4_address: 192.168.1.11

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

